baseURL = "https://precast.bangunan.co/"
languageCode = "id"
title = "Panel & Buis Beton | Jual Pagar Panel Beton, Dak Panel Beton dan Buis Beton"
theme = "saeseen-hugo"
summaryLength = 25
paginate = 6

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  category = "/:slug/"

[params]
  # Site-wide settings
  meta_description = "Jual Panel dan Buis Beton - Pagar Panel Beton, Dak Panel Beton, serta Buis Beton dengan harga terjangkau dan kualitas terbaik."
  viewport = "width=device-width, initial-scale=1.0"
  fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
  logo = "/images/logo/bangunanco-logo-web.png"
  logo_amp = "/images/logo/bangunanco-512x512.png"
  footer_logo = "/images/logo/bangunanco-logo-putih.png"
  favicon = "/images/logo/bangunanco-512x512.png"
  featured_image = "/images/admin/featured-image.png"
  author = "K. Yaman"
  telepon = "//+6285776786091"
  whatsapp = "//api.whatsapp.com/send?phone=6285776786091&text=*Halo bangunan.co*%20%3A"
  enableWhatApps = true
  enableTelepon = true
  tocMinWordCount = 300
  tableOfContent = "Daftar Isi:"
  geo_latitude = -6.595038
  geo_longitude = 106.817787
  opening_hours = "Mo-Sa 08:00-17:00"

  # Schema settings
  keywords = ["jual pagar panel beton", "buis beton", "dak panel beton", "pagar beton", "harga buis beton", "precast panel beton"]
  base_price = 1000000
  price_range = 300000
  free_shipping = true
  materials = [
  "Pagar Panel Beton Pracetak",
  "Dak Panel Beton Pracetak",
  "Buis Beton Pracetak",
  "Pagar Panel Beton Custom",
  "Dak Panel Beton Custom"
  ]
  categories = ["Panel Beton", "Buis Beton", "Material Bangunan"]
  payment_methods = ["COD (Cash On Delivery)", "Transfer Bank", "Bayar DP 50%", "Transfer Setelah Pengiriman"]
  area_served = [
    "Jakarta", "Bogor", "Depok", "Tangerang", "Bekasi", "Bandung", "Cimahi", "Sukabumi", "Cirebon", "Garut", "Tasikmalaya", "Sumedang", "Subang", "Karawang", "Purwakarta", "Cianjur", "Majalengka", "Indramayu", "Kuningan", "Banjar", "Pangandaran", "Kabupaten Bandung", "Kabupaten Bogor", "Kabupaten Bekasi", "Kabupaten Cirebon", "Kabupaten Garut", "Kabupaten Indramayu", "Kabupaten Karawang", "Kabupaten Kuningan", "Kabupaten Majalengka", "Kabupaten Pangandaran", "Kabupaten Purwakarta", "Kabupaten Subang", "Kabupaten Sukabumi", "Kabupaten Sumedang", "Kabupaten Tasikmalaya", "Serang", "Cilegon", "Tangerang Selatan", "Lebak", "Pandeglang", "Kabupaten Tangerang", "Kabupaten Serang", "Semarang", "Surakarta", "Magelang", "Salatiga", "Pekalongan", "Tegal", "Cilacap", "Purwokerto", "Pati", "Jepara", "Kudus", "Demak", "Blora", "Grobogan", "Kendal", "Temanggung", "Wonosobo", "Purworejo", "Kabupaten Magelang", "Kabupaten Boyolali", "Kabupaten Klaten", "Kabupaten Sragen", "Kabupaten Karanganyar", "Kabupaten Sukoharjo", "Kabupaten Wonogiri", "Kabupaten Pati", "Kabupaten Blora", "Kabupaten Grobogan", "Kabupaten Kudus", "Kabupaten Jepara", "Kabupaten Demak", "Kabupaten Batang", "Kabupaten Pekalongan", "Kabupaten Pemalang", "Kabupaten Tegal", "Kabupaten Brebes", "Kabupaten Cilacap", "Kabupaten Banyumas", "Kabupaten Purbalingga", "Kabupaten Banjarnegara", "Kabupaten Kebumen", "Kabupaten Temanggung", "Kabupaten Wonosobo", "Kabupaten Kendal", "Kabupaten Semarang", "Kabupaten Purworejo", "Surabaya", "Malang", "Batu", "Blitar", "Kediri", "Mojokerto", "Madiun", "Pasuruan", "Probolinggo", "Jember", "Lumajang", "Bondowoso", "Banyuwangi", "Situbondo", "Ngawi", "Magetan", "Pacitan", "Ponorogo", "Trenggalek", "Tulungagung", "Kabupaten Sidoarjo", "Kabupaten Gresik", "Kabupaten Lamongan", "Kabupaten Bojonegoro", "Kabupaten Tuban", "Kabupaten Jombang", "Kabupaten Nganjuk", "Kabupaten Madiun", "Kabupaten Magetan", "Kabupaten Ngawi", "Kabupaten Pacitan", "Kabupaten Ponorogo", "Kabupaten Blitar", "Kabupaten Tulungagung", "Kabupaten Kediri", "Kabupaten Malang", "Kabupaten Probolinggo", "Kabupaten Pasuruan", "Kabupaten Lumajang", "Kabupaten Jember", "Kabupaten Bondowoso", "Kabupaten Banyuwangi", "Kabupaten Situbondo"
  ]
  return_policies = [
  "Barang bisa dikembalikan dalam 1 hari jika tidak sesuai.",
  "Barang dapat ditolak jika spesifikasi tidak sesuai.",
  "Pengembalian gratis untuk produk yang tidak sesuai pesanan."
  ]

 # Hero Section
  hero_image = "/images/admin/bg_bangunanco.png"
  hero_title = "Panel & Buis Beton Berkualitas"
  hero_description = "Kami menawarkan berbagai jenis panel beton dan buis beton berkualitas tinggi untuk keperluan konstruksi Anda. Solusi ideal untuk pondasi, pagar, dan saluran air dengan bahan yang kuat dan tahan lama."
  hero_cta_text = "Pelajari Lebih Lanjut"
  services_cta_text = "Cek Katalog Produk"

# Footer Section
  footer_about_title = "Mengapa Memilih Kami"
  footer_about_description = "Kami menyediakan berbagai produk panel dan buis beton dengan kualitas terbaik dan harga kompetitif. Layanan pengiriman cepat dan konsultasi gratis untuk membantu Anda memilih produk beton yang sesuai dengan kebutuhan konstruksi Anda."
  footer_services_title = "Kenapa Pilih Kami"
  footer_contact_title = "Kontak Kami"
  footer_bottom_text = "@2024 Bangunan.co. Semua Hak Dilindungi."

  # Testimonials Section
  testimonials_title = "Apa Kata Klien Kami"

  [[params.footer_services]]
  text = "precast.bangunan.co menawarkan produk pagar panel beton, dak panel beton, dan buis beton berkualitas tinggi dengan harga yang bersaing. Kami mengutamakan kepuasan pelanggan dengan produk yang kuat, tahan lama, dan mudah dipasang. Pilih kami untuk kebutuhan konstruksi beton Anda dengan kualitas terbaik."

  [[params.footer_contact]]
    icon = "fas fa-map-marker-alt"
    text = "Jalan Lkr. Dramaga No. 09, Bogor - JaBar"
  [[params.footer_contact]]
    icon = "fas fa-phone-alt"
    text = "+62 857-7678-6091"
  [[params.footer_contact]]
    icon = "fas fa-envelope"
    text = "bangunanco@gmail.com"

[[params.testimonials]]
  avatar = "/images/admin/avatar1.png"
  name = "{Budi|Joko|Andi|Eko|Rudi|Fajar|Hendra|Samsul|Agus|Dedi}"
  message = "{Saya {menggunakan|memanfaatkan|memakai} pagar panel beton dari precast.bangunan.co untuk {proyek|pembangunan|konstruksi} rumah saya. Kualitasnya {sangat baik|luar biasa|menakjubkan} dan pemasangannya {rapi|tertata|bersih}.|Pagar panel beton dari precast.bangunan.co {berkualitas tinggi|premium|kuat} dan pemasangannya {sangat rapi|baik sekali|terorganisir}.}"
  response = "{Terima kasih atas {kepercayaan|dukungan|pilihan} Anda! Kami senang dapat {menyediakan|menghadirkan|memenuhi} produk beton berkualitas untuk {proyek|pembangunan} Anda.|Kami {sangat menghargai|berterima kasih atas} kepercayaan Anda. Senang dapat berkontribusi dalam proyek Anda!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar2.png"
  name = "{Siti|Dewi|Rina|Maya|Lina|Sari|Fitri|Nur|Diah|Ayu}"
  message = "{precast.bangunan.co {sangat membantu|mempermudah|mengarahkan} dalam memilih panel beton untuk proyek saya. Produk yang {saya beli|saya pesan|dikirim} {berkualitas tinggi|bermutu|premium} dan sesuai dengan kebutuhan saya.|Saya terbantu oleh precast.bangunan.co dalam memilih produk beton untuk proyek saya. Produknya {berkualitas|premium|bermutu tinggi} dan sesuai dengan spesifikasi yang saya butuhkan.}"
  response = "{Kami sangat menghargai ulasan Anda. {Senang mendengar|Bahagia mengetahui} bahwa Anda puas dengan panel beton dari kami.|Terima kasih atas {ulasan|masukan} Anda! Kami {gembira|senang} Anda puas dengan layanan dan produk kami.}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar3.png"
  name = "{Joko|Bambang|Hadi|Tono|Gilang|Bayu|Faisal|Rizal|Ali|Ahmad}"
  message = "{Panel beton dari precast.bangunan.co {sangat kokoh|kuat|berkualitas} dan {cocok|sesuai|ideal} untuk proyek {perumahan|real estate|properti} saya. Proses pengirimannya juga {cepat|tepat waktu|efisien} dan {lancar|terorganisir|tepat}.|Beton precast.bangunan.co {kokoh|kuat} dan sesuai dengan kebutuhan proyek saya. Pengirimannya {tepat waktu|cepat|lancar} dan tanpa kendala.}"
  response = "{Terima kasih! Kami {berkomitmen|fokus|dedikasi} untuk menyediakan produk beton berkualitas dengan {layanan|pengiriman} terbaik.|Kami {apresiasi|menghargai} ulasan Anda. Terima kasih atas {kepercayaan|pilihan} Anda menggunakan produk kami!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar4.png"
  name = "{Andi|Bayu|Fajar|Hendra|Dian|Rizky|Yoga|Yudi|Ari|Gani}"
  message = "{Saya {sangat puas|senang|terkesan} dengan buis beton dari precast.bangunan.co. Kualitasnya {sangat baik|luar biasa|berkualitas tinggi} dan {tahan lama|awet|kokoh} untuk proyek saya.|Buis beton precast.bangunan.co {sangat kuat|kokoh|berkualitas tinggi} dan {tahan lama|awet} untuk proyek yang saya kerjakan.}"
  response = "{Senang mendengar Anda puas dengan {buis beton|produk} kami. Terima kasih atas {kepercayaannya|pilihannya|dukungan Anda}!|Kami {bahagia|senang|gembira} Anda puas dengan layanan dan produk kami. Terima kasih atas {kepercayaannya|dukungan Anda}!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar5.png"
  name = "{Rina|Siti|Dewi|Lina|Ayu|Fitri|Sari|Diah|Nur|Maya}"
  message = "{Pelayanan precast.bangunan.co {sangat memuaskan|luar biasa|baik sekali}. Produk pagar panel beton yang {saya beli|dikirim} {berkualitas tinggi|bermutu|premium} dan sesuai dengan {harapan|ekspektasi|spesifikasi saya}.|Saya sangat puas dengan {produk|layanan} precast.bangunan.co. Pagar panel beton yang {saya beli|dikirim} {berkualitas tinggi|premium|bermutu} dan {sesuai dengan harapan|memenuhi ekspektasi|sesuai standar}.}"
  response = "{Terima kasih! Kami senang dapat {membantu|mewujudkan|melayani} proyek Anda dengan {produk|beton} terbaik.|Kami menghargai {ulasan|masukan} Anda. Terima kasih telah {memilih|mempercayai|menggunakan} produk kami!}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar6.png"
  name = "{Eko|Agus|Dedi|Toni|Yanto|Wawan|Benny|Rio|Iwan|Galih}"
  message = "{Buis beton dari precast.bangunan.co {sangat sesuai|tepat|cocok} dengan {spesifikasi|standar|kebutuhan} proyek {saluran air|infrastruktur|pembangunan} yang saya kerjakan. Pengirimannya {cepat|tepat waktu|aman} dan {lancar|terorganisir|sesuai jadwal}.|Saya puas dengan {produk|buis beton} precast.bangunan.co untuk proyek saluran air saya. Pengirimannya {cepat|tepat waktu|lancar} dan {sesuai harapan|memenuhi ekspektasi|aman}.}"
  response = "{Kami {senang|bahagia|gembira} mendengar bahwa Anda puas dengan {produk|layanan} kami. Terima kasih atas {ulasannya|kepercayaannya}!|Terima kasih telah {mempercayai|memilih|menggunakan} produk kami. Kami {senang|gembira} Anda puas dengan hasilnya.}"
  rating = 4

[[params.tabelItems]]
  name = "Pagar Panel Beton Pracetak"
  price = "450.000 /unit"
[[params.tabelItems]]
  name = "Dak Panel Beton Pracetak"
  price = "600.000 /unit"
[[params.tabelItems]]
  name = "Buis Beton Pracetak"
  price = "450.000 /unit"
[[params.tabelItems]]
  name = "Box Culvert"
  price = "500.000 /unit"
[[params.tabelItems]]
  name = "U-ditch Beton"
  price = "450.000 /unit"

[params.appliList]
  "Pagar Panel Beton Pracetak" = "proyek pagar dinding pembatas"
  "Dak Panel Beton Pracetak" = "struktur atap bangunan"
  "Buis Beton Pracetak" = "saluran air, got, septic tank"
  "Box Culvert" = "saluran air, got tanpa penutup"
  "U-ditch Beton" = "saluran air, got"

[params.kegunaanList]
  "Pagar Panel Beton Pracetak" = "digunakan untuk pagar dinding yang kuat dan tahan lama"
  "Dak Panel Beton Pracetak" = "cocok untuk penutup atap bangunan"
  "Buis Beton Pracetak" = "ideal untuk saluran air dan sistem sanitasi"
  "Box Culvert" = "memenuhi kebutuhan proyek drainase dengan cepat"
  "U-ditch Beton" = "digunakan untuk proyek drainase yang fleksibel"

  # Menu Section
  [[params.menu_items]]
    title = "Beranda"
    url = "/"
  [[params.menu_items]]
    title = "Profile"
    url = "https://bangunan.co/profile/"
  [[params.menu_items]]
    title = "Daftar Harga"
    url = "https://bangunan.co/daftar-harga/"

[params.header]
   title = "Jual Panel & Buis Beton Berkualitas | "
   highlight = "Bangunan.co"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp/index"
    path = ""
    isPlainText = false
    permalinkable = true
    rel = "amphtml"